# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0032_fix_org_with_nexmo_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('value', models.FloatField(help_text='The value in cents of the MoIP order', verbose_name='Value')),
                ('credits', models.IntegerField(help_text='The number of credits bought in this top up', verbose_name='Number of Credits')),
                ('plan', models.CharField(max_length=255, verbose_name='Plan')),
                ('transaction_id', models.CharField(help_text='PayPal request transaction ID', max_length=255, unique=True, verbose_name='Transaction ID')),
                ('billing_agreement_id', models.CharField(help_text='PayPal billing agreement ID', max_length=255, null=True, verbose_name='Billing Agreement ID')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='orgs_orderpayment_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='orgs_orderpayment_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='org',
            name='brand',
            field=models.CharField(default='push.ilhasoft.mobi', help_text='The brand used in emails', max_length=128, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='org',
            field=models.ForeignKey(help_text='The organization that payment was requested', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orgs.Org'),
        ),
    ]
