image: python:3.6.4

pipelines:
  default:
    - step:
        name: Python Requirements
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip --version
          - pip install -r pip-freeze.txt --upgrade
          - pip install coveralls
          - pip install flake8
    - step:
        name: Node Requirements
        image: node
        caches:
          - node
        script:
          - npm install
          - npm run build
    - step:
        name: Goflow and Indexer
        image: golang
        script:
          - GOFLOW_VERSION=0.10.20
          - RPINDEXER_VERSION=1.0.22
          - wget https://github.com/nyaruka/goflow/releases/download/v${GOFLOW_VERSION}/goflow_${GOFLOW_VERSION}_linux_amd64.tar.gz
          - tar -xvf goflow_${GOFLOW_VERSION}_linux_amd64.tar.gz
          - wget https://github.com/nyaruka/rp-indexer/releases/download/v${RPINDEXER_VERSION}/rp-indexer_${RPINDEXER_VERSION}_linux_amd64.tar.gz
          - tar -xvf rp-indexer_${RPINDEXER_VERSION}_linux_amd64.tar.gz
    - step:
        name: Tests
        script:
          - pip list

definitions: 
  services: 
    postgres: 
      image: mdillon/postgis
      environment: 
        POSTGRES_DB: temba 
        POSTGRES_USER: temba 
        POSTGRES_PASSWORD: temba
    redis:
      image: redis
    elasticsearch:
      image: elastic/elasticsearch:6.3.1
