version: "3.3"

services:

  push_base:
    image: ilha/push:base
    build:
      context: .
      dockerfile: push_base.Dockerfile
  push_prod:
    image: ilha/push:prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
