version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01
      enabled: true

    steps:
      - run:
          name: install dependencies
          command: |
            # postgresql, python and redis
            sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main"
            sudo wget -q -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo add-apt-repository ppa:jonathonf/python-3.6
            sudo apt update
            sudo apt install postgresql-9.6 postgresql-9.6-postgis-2.3 python3.6 redis-server -y

            # database user
            /usr/lib/postgresql/9.6/bin/pg_ctl -D /var/lib/postgresql/9.6/main -l logfile start
            sudo -u postgres psql postgres -c "CREATE USER temba WITH PASSWORD 'temba';"
            sudo -u postgres psql postgres -c "ALTER ROLE temba WITH SUPERUSER;"
            sudo -u postgres psql postgres -d 'template1' -c "CREATE EXTENSION postgis;"
            sudo -u postgres psql postgres -d 'template1' -c "CREATE EXTENSION postgis_topology;"
            sudo -u postgres psql postgres -d 'template1' -c "CREATE EXTENSION hstore;"
            sudo -u postgres psql postgres -c "CREATE DATABASE temba;"

            # elastic search
            wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.1.tar.gz
            tar -xzf elasticsearch-6.3.1.tar.gz
            ./elasticsearch-6.3.1/bin/elasticsearch &
