# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0046_merge'),
        ('channels', '0049_auto_20170106_0910'),
    ]

    operations = [
    ]
