# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0078_auto_20161216_1803'),
        ('flows', '0075_merge'),
    ]

    operations = [
    ]
