# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0128_change_quick_replies_format'),
        ('flows', '0147_new_engine_changes'),
    ]

    operations = [
    ]
