# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-29 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flows", "0169_auto_20180613_1940"), ("flows", "0149_auto_20180904_1236")]

    operations = []
